//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDope_AnswerFormat.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenDope_AnswerFormat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Add New Part...).
        /// </summary>
        internal static string AddNewDataSource {
            get {
                return ResourceManager.GetString("AddNewDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attribute.
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Banner {
            get {
                object obj = ResourceManager.GetObject("Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CData Section.
        /// </summary>
        internal static string CDATA {
            get {
                return ResourceManager.GetString("CDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The friendly name for this custom XML part could not be changed..
        /// </summary>
        internal static string ChangePartNameErrorMessage {
            get {
                return ResourceManager.GetString("ChangePartNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete XML Document.
        /// </summary>
        internal static string CompleteXMLDocument {
            get {
                return ResourceManager.GetString("CompleteXMLDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Core File Properties.
        /// </summary>
        internal static string CoreFilePropertiesName {
            get {
                return ResourceManager.GetString("CoreFilePropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cover Page Properties.
        /// </summary>
        internal static string CoverPagePropertiesName {
            get {
                return ResourceManager.GetString("CoverPagePropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here and enter a date..
        /// </summary>
        internal static string DatePlaceholder {
            get {
                return ResourceManager.GetString("DatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting this node will affect any controls in your document that are bound to it. Are you sure?.
        /// </summary>
        internal static string DeleteNodeMessage {
            get {
                return ResourceManager.GetString("DeleteNodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting this data source will affect any content controls in your document that are bound to it.
        ///
        ///Are you sure you want to delete it?.
        /// </summary>
        internal static string DeletePartMessage {
            get {
                return ResourceManager.GetString("DeletePartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML Mapping Task Pane.
        /// </summary>
        internal static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose....
        /// </summary>
        internal static string DropDownPlaceholder {
            get {
                return ResourceManager.GetString("DropDownPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A combo box content control cannot be applied to the current selection.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddComboBox {
            get {
                return ResourceManager.GetString("ErrorAddComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A date picker content control cannot be applied to the current selection.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddDate {
            get {
                return ResourceManager.GetString("ErrorAddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A drop-down list content control cannot be applied to the current selection.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddDropDown {
            get {
                return ResourceManager.GetString("ErrorAddDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This node could not be added:
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddingNode {
            get {
                return ResourceManager.GetString("ErrorAddingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A picture content control cannot be applied to the current selection.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddPicture {
            get {
                return ResourceManager.GetString("ErrorAddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A plain text content control cannot be applied to the current selection.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorAddPlainText {
            get {
                return ResourceManager.GetString("ErrorAddPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The selected data source could not be deleted:
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorDeletePart {
            get {
                return ResourceManager.GetString("ErrorDeletePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This node could not be deleted:
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorDeletingNode {
            get {
                return ResourceManager.GetString("ErrorDeletingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An element or attribute must have a non-empty name..
        /// </summary>
        internal static string ErrorNoName {
            get {
                return ResourceManager.GetString("ErrorNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This XML file could not be added: 
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorOnPartAdd {
            get {
                return ResourceManager.GetString("ErrorOnPartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The text node could not be renamed:
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorRenamingNode {
            get {
                return ResourceManager.GetString("ErrorRenamingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your updated settings could not be saved. Any changes will be lost..
        /// </summary>
        internal static string ErrorSaveSettings {
            get {
                return ResourceManager.GetString("ErrorSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extended File Properties.
        /// </summary>
        internal static string ExtendedFilePropertiesName {
            get {
                return ResourceManager.GetString("ExtendedFilePropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified file could not be located..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file specified does not contain valid XML:
        ///
        ///{0}.
        /// </summary>
        internal static string FileNotValidXml {
            get {
                return ResourceManager.GetString("FileNotValidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Line {
            get {
                object obj = ResourceManager.GetObject("Line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading...
        ///{0}%.
        /// </summary>
        internal static string LoadingMessageWithPercentage {
            get {
                return ResourceManager.GetString("LoadingMessageWithPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1033.
        /// </summary>
        internal static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Namespace.
        /// </summary>
        internal static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next &gt;.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (no namespace).
        /// </summary>
        internal static string NoNamespace {
            get {
                return ResourceManager.GetString("NoNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} ({1}).
        /// </summary>
        internal static string NumberedItem {
            get {
                return ResourceManager.GetString("NumberedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to enter text..
        /// </summary>
        internal static string PlainTextPlaceholder {
            get {
                return ResourceManager.GetString("PlainTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prefix Mappings.
        /// </summary>
        internal static string Prefixes {
            get {
                return ResourceManager.GetString("Prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Processing Instruction.
        /// </summary>
        internal static string ProcessingInstruction {
            get {
                return ResourceManager.GetString("ProcessingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RibbonIcon {
            get {
                object obj = ResourceManager.GetObject("RibbonIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The string specified does not contain valid XML:
        ///
        ///{0}.
        /// </summary>
        internal static string StringNotValidXml {
            get {
                return ResourceManager.GetString("StringNotValidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML Mapping.
        /// </summary>
        internal static string TaskPaneName {
            get {
                return ResourceManager.GetString("TaskPaneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Node Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML.
        /// </summary>
        internal static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XPath.
        /// </summary>
        internal static string XPath {
            get {
                return ResourceManager.GetString("XPath", resourceCulture);
            }
        }
    }
}
